module.exports={
	user:require("../Model/user"),
	role:require("../Model/role"),
	permission:require("../Model/permission"),
	functionModel:require("../Model/functionModel"),
	column:require("../Model/column"),
	content:require("../Model/content"),
	navbar:require("../Model/navbar")
}